export interface LanguageOption {
  code: string;
  label: string;
  nativeName: string;
  dir: 'ltr' | 'rtl';
  flag: string;
}

export const DEFAULT_LANGUAGE = 'en';
export const LANGUAGE_STORAGE_KEY = 'app_selected_language';

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  {
    code: 'en',
    label: 'English',
    nativeName: 'English',
    dir: 'ltr',
    flag: '🌐',
  },
  {
    code: 'ar',
    label: 'Arabic',
    nativeName: 'العربية',
    dir: 'rtl',
    flag: '🌐',
  },
];

export const RTL_LANGUAGES = ['ar', 'fa', 'he', 'ur'];

export function isRtlLanguage(langCode: string | null | undefined): boolean {
  if (!langCode) {
    return false;
  }
  return RTL_LANGUAGES.includes(langCode.toLowerCase());
}

export const TRANSLATION_TOKENS = {
  APP: {
    TITLE: {
      PREFIX: 'APP.TITLE.PREFIX',
    },
  },
  DEFAULT: {
    PAGE: {
      TITLE: 'DEFAULT.PAGE.TITLE',
      DESCRIPTION: 'DEFAULT.PAGE.DESCRIPTION',
    },
  },
  NAV: {
    DASHBOARD: 'NAV.DASHBOARD',
    ITEMS: 'NAV.ITEMS',
    SETTINGS: 'NAV.SETTINGS',
    LOGIN: 'NAV.LOGIN',
    LOGOUT: 'NAV.LOGOUT',
  },
  COMMON: {
    BRAND_NAME: 'COMMON.BRAND_NAME',
    LANGUAGE: 'COMMON.LANGUAGE',
    SELECT_LANGUAGE: 'COMMON.SELECT_LANGUAGE',
    SAVE: 'COMMON.SAVE',
    SAVING: 'COMMON.SAVING',
    CANCEL: 'COMMON.CANCEL',
    DELETE: 'COMMON.DELETE',
    DELETING: 'COMMON.DELETING',
    EDIT: 'COMMON.EDIT',
    ADD: 'COMMON.ADD',
    SEARCH: 'COMMON.SEARCH',
    STATUS: 'COMMON.STATUS',
    ACTIONS: 'COMMON.ACTIONS',
    CONFIRM: 'COMMON.CONFIRM',
    CLOSE_MENU: 'COMMON.CLOSE_MENU',
    OPEN_MENU: 'COMMON.OPEN_MENU',
    TO_CONFIRM_TYPE: 'COMMON.TO_CONFIRM_TYPE',
    CONFIRM_PHRASE_PLACEHOLDER: 'COMMON.CONFIRM_PHRASE_PLACEHOLDER',
    BELOW_COLON: 'COMMON.BELOW_COLON',
    BACK: 'COMMON.BACK',
    NEXT: 'COMMON.NEXT',
    PREVIOUS: 'COMMON.PREVIOUS',
    SUBMIT: 'COMMON.SUBMIT',
    REQUIRED: 'COMMON.REQUIRED',
    LOADING: 'COMMON.LOADING',
    NO_DATA: 'COMMON.NO_DATA',
    YES: 'COMMON.YES',
    NO: 'COMMON.NO',
    PAGE_NOT_FOUND: 'COMMON.PAGE_NOT_FOUND',
    GO_BACK_HOME: 'COMMON.GO_BACK_HOME',
    RETRY: 'COMMON.RETRY',
    LOADING_CHART: 'COMMON.LOADING_CHART',
  },
  AUTH: {
    WELCOME_BACK: 'AUTH.WELCOME_BACK',
    LOGIN_SUBTITLE: 'AUTH.LOGIN_SUBTITLE',
    EMAIL_LABEL: 'AUTH.EMAIL_LABEL',
    EMAIL_PLACEHOLDER: 'AUTH.EMAIL_PLACEHOLDER',
    PASSWORD_LABEL: 'AUTH.PASSWORD_LABEL',
    PASSWORD_PLACEHOLDER: 'AUTH.PASSWORD_PLACEHOLDER',
    LOGIN_BUTTON: 'AUTH.LOGIN_BUTTON',
    SELECT_ROLE: 'AUTH.SELECT_ROLE',
    DEMO_NOTE: 'AUTH.DEMO_NOTE',
    REVEAL_PASSWORDS: 'AUTH.REVEAL_PASSWORDS',
    HIDE_PASSWORDS: 'AUTH.HIDE_PASSWORDS',
    EMAIL_REQUIRED: 'AUTH.EMAIL_REQUIRED',
    PASSWORD_REQUIRED: 'AUTH.PASSWORD_REQUIRED',
    VALID_EMAIL: 'AUTH.VALID_EMAIL',
    LOGIN_SUCCESS: 'AUTH.LOGIN_SUCCESS',
    INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
  },
  DASHBOARD: {
    TITLE: 'DASHBOARD.TITLE',
    SUBTITLE: 'DASHBOARD.SUBTITLE',
    TOTAL_USERS: 'DASHBOARD.TOTAL_USERS',
    TOTAL_REVENUE: 'DASHBOARD.TOTAL_REVENUE',
    ACTIVE_PROJECTS: 'DASHBOARD.ACTIVE_PROJECTS',
    CONVERSION_RATE: 'DASHBOARD.CONVERSION_RATE',
    MONTHLY_TRENDS: 'DASHBOARD.MONTHLY_TRENDS',
    CATEGORY_DISTRIBUTION: 'DASHBOARD.CATEGORY_DISTRIBUTION',
    RECENT_ACTIVITIES: 'DASHBOARD.RECENT_ACTIVITIES',
  },
  ITEMS: {
    TITLE: 'ITEMS.TITLE',
    SUBTITLE: 'ITEMS.SUBTITLE',
    ADD_ITEM: 'ITEMS.ADD_ITEM',
    EDIT_ITEM: 'ITEMS.EDIT_ITEM',
    DELETE_ITEM: 'ITEMS.DELETE_ITEM',
    DELETE_CONFIRMATION: 'ITEMS.DELETE_CONFIRMATION',
    NAME: 'ITEMS.NAME',
    CATEGORY: 'ITEMS.CATEGORY',
    PRICE: 'ITEMS.PRICE',
    STOCK: 'ITEMS.STOCK',
    DESCRIPTION: 'ITEMS.DESCRIPTION',
    NAME_REQUIRED: 'ITEMS.NAME_REQUIRED',
    CATEGORY_REQUIRED: 'ITEMS.CATEGORY_REQUIRED',
    PRICE_REQUIRED: 'ITEMS.PRICE_REQUIRED',
  },
  SETTINGS: {
    TITLE: 'SETTINGS.TITLE',
    SUBTITLE: 'SETTINGS.SUBTITLE',
    PROFILE_SETTINGS: 'SETTINGS.PROFILE_SETTINGS',
    LANGUAGE_AND_REGION: 'SETTINGS.LANGUAGE_AND_REGION',
    THEME_PREFERENCES: 'SETTINGS.THEME_PREFERENCES',
    DARK_MODE: 'SETTINGS.DARK_MODE',
    NOTIFICATION_PREFERENCES: 'SETTINGS.NOTIFICATION_PREFERENCES',
    SAVE_PREFERENCES: 'SETTINGS.SAVE_PREFERENCES',
  },
} as const;
